export const dark = () => ({
  colors: {
    types: {
      normal: "#A8A77A",
      fire: "#EE8130",
      water: "#6390F0",
      electric: "#F7D02C",
      grass: "#7AC74C",
      ice: "#96D9D6",
      fighting: "#C22E28",
      poison: "#A33EA1",
      ground: "#E2BF65",
      flying: "#A98FF3",
      psychic: "#F95587",
      bug: "#A6B91A",
      rock: "#B6A136",
      ghost: "#735797",
      dragon: "#6F35FC",
      dark: "#705746",
      steel: "#B7B7CE",
      fairy: "#D685AD",
      eletric: "#FBD100",
    },
  },
  icons: {
    types: {
      normal: `url("/icon/typesIcons/normal.svg")`,
      fire: `url("/icon/typesIcons/fire.svg")`,
      water: `url("/icon/typesIcons/water.svg")`,
      electric: `url("/icon/typesIcons/electric.svg")`,
      grass: `url("/icon/typesIcons/grass.svg")`,
      ice: `url("/icon/typesIcons/ice.svg")`,
      fighting: `url("/icon/typesIcons/fighting.svg")`,
      poison: `url("/icon/typesIcons/poison.svg")`,
      ground: `url("/icon/typesIcons/ground.svg")`,
      flying: `url("/icon/typesIcons/flying.svg")`,
      psychic: `url("/icon/typesIcons/psychic.svg")`,
      bug: `url("/icon/typesIcons/bug.svg")`,
      rock: `url("/icon/typesIcons/rock.svg")`,
      ghost: `url("/icon/typesIcons/ghost.svg")`,
      dragon: `url("/icon/typesIcons/dragon.svg")`,
      dark: `url("/icon/typesIcons/dark.svg")`,
      steel: `url("/icon/typesIcons/steel.svg")`,
      fairy: `url("/icon/typesIcons/fairy.svg")`,
      eletric: `url("/icon/typesIcons/eletric.svg")`,
    },
  },
});
