import Head from "next/head";
import SearchBar from "@/components/SearchBar";
import FilterOptions from "@/components/FilterOptions";
import CardPokemon from "@/components/CardPokemon";
import React, { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  // const [pokemons, setPokemons] = useState<any[]>();
  // const [loading, setLoading] = useState(false);

  // useEffect(() => {
  //   getPokemons();
  // }, []);

  // const getPokemons = () => {
  //   setLoading(false);
  //   var endpoints = [];
  //   for (var i = 1; i < 1008; i++) {
  //     endpoints.push(`https://pokeapi.co/api/v2/pokemon/${i}/`);
  //   }
  //   var response = axios
  //     .all(endpoints.map(async (endpoint) => await axios.get(endpoint)))
  //     .then((res) => {
  //       setPokemons(res);
  //       console.log(res);
  //       setLoading(true);
  //     });
  //   console.log(endpoints);
  // };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar />
      <FilterOptions />
      <CardPokemon />
    </>
  );
}
